language: generic
dist: xenial
sudo: required
notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libxml2-utils
script:
  - cd test && bash test.sh
